version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "article_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5435:5432"
  